//
//  LocalizationStrings+Common.swift
//  WeChatSwift
//
//  Created by xu.shuifeng on 2019/9/10.
//  Copyright © 2019 alexiscn. All rights reserved.
//

import Foundation

extension LocalizationStrings {
    static let Common_Add = "Common_Add"
    static let Common_All = "Common_All"
    static let Common_Allow = "Common_Allow"
    static let Common_Call = "Common_Call"
    static let Common_Cancel = "Common_Cancel"
    static let Common_ClearAll = "Common_ClearAll"
    static let Common_Close = "Common_Close"
    static let Common_Commit = "Common_Commit"
    static let Common_Confirm = "Common_Confirm"
    static let Common_Continue = "Common_Continue"
    static let Common_CopyLink = "Common_CopyLink"
    static let Common_Debug = "Common_Debug"
    static let Common_DefaultLoadingText = "Common_DefaultLoadingText"
    static let Common_Delete = "Common_Delete"
    static let Common_DeleteAll = "Common_DeleteAll"
    static let Common_Deleting = "Common_Deleting"
    static let Common_DisAllowed = "Common_DisAllowed"
    static let Common_Done = "Common_Done"
    static let Common_Download = "Common_Download"
    static let Common_Edit = "Common_Edit"
    static let Common_Error_Network = "Common_Error_Network"
    static let Common_Exit = "Common_Exit"
    static let Common_Forward = "Common_Forward"
    static let Common_FreeForSale = "Common_FreeForSale"
    static let Common_I_Know = "Common_I_Know"
    static let Common_Know = "Common_Know"
    static let Common_List = "Common_List"
    static let Common_Look_Detail = "Common_Look_Detail"
    static let Common_MemoryWarning = "Common_MemoryWarning"
    static let Common_More = "Common_More"
    static let Common_NeedBindQQ = "Common_NeedBindQQ"
    static let Common_NextStep = "Common_NextStep"
    static let Common_No = "Common_No"
    static let Common_Not_SelectAll = "Common_Not_SelectAll"
    static let Common_NoTitle = "Common_NoTitle"
    static let Common_OfficialAliasName = "Common_OfficialAliasName"
    static let Common_OfficialNickName = "Common_OfficialNickName"
    static let Common_OK = "Common_OK"
    static let Common_ProductName = "Common_ProductName"
    static let Common_Reply = "Common_Reply"
    static let Common_Resend = "Common_Resend"
    static let Common_Retry = "Common_Retry"
    static let Common_Return = "Common_Return"
    static let Common_Save = "Common_Save"
    static let Common_Save_OK = "Common_Save_OK"
    static let Common_Select = "Common_Select"
    static let Common_SelectAll = "Common_SelectAll"
    static let Common_Send = "Common_Send"
    static let Common_Set = "Common_Set"
    static let Common_Share = "Common_Share"
    static let Common_Skip = "Common_Skip"
    static let Common_Submit = "Common_Submit"
    static let Common_TipTitle = "Common_TipTitle"
    static let Common_TipTitle_WenXing = "Common_TipTitle_WenXing"
    static let Common_Undo = "Common_Undo"
    static let Common_UnSave = "Common_UnSave"
    static let Common_Use = "Common_Use"
    static let Common_Wait = "Common_Wait"
    static let Common_Yes = "Common_Yes"
}
