//
//  LocalizationStrings+GroupPay.swift
//  WeChatSwift
//
//  Created by xu.shuifeng on 2019/9/10.
//  Copyright © 2019 alexiscn. All rights reserved.
//

import Foundation

extension LocalizationStrings {
    static let GroupPay_AA_Launcher_HasFinish_Desc = "GroupPay_AA_Launcher_HasFinish_Desc"
    static let GroupPay_AA_Launcher_HasPaid_Desc_Fotmat = "GroupPay_AA_Launcher_HasPaid_Desc_Fotmat"
    static let GroupPay_AA_Launcher_HasStop_Desc = "GroupPay_AA_Launcher_HasStop_Desc"
    static let GroupPay_AA_Launcher_Launch_Desc = "GroupPay_AA_Launcher_Launch_Desc"
    static let GroupPay_AA_MaxPerAmount_Tips_Format = "GroupPay_AA_MaxPerAmount_Tips_Format"
    static let GroupPay_AA_MaxTotalAmount_Tips_Format = "GroupPay_AA_MaxTotalAmount_Tips_Format"
    static let GroupPay_AA_Notiner_Default_Desc = "GroupPay_AA_Notiner_Default_Desc"
    static let GroupPay_AA_Payer_HasBeenClose_Desc_format = "GroupPay_AA_Payer_HasBeenClose_Desc_format"
    static let GroupPay_AA_Payer_HasPaid_Desc_Format = "GroupPay_AA_Payer_HasPaid_Desc_Format"
    static let GroupPay_AA_Payer_UnPaid_Desc_Format = "GroupPay_AA_Payer_UnPaid_Desc_Format"
    static let GroupPay_AA_SelectMember_MaxTotalNum_ShouldMoreThan1_Tips_Format = "GroupPay_AA_SelectMember_MaxTotalNum_ShouldMoreThan1_Tips_Format"
    static let GroupPay_AA_SelectTotalMember_Tips_Format = "GroupPay_AA_SelectTotalMember_Tips_Format"
    static let GroupPay_ActionSheet_LaunchNewGroupPay = "GroupPay_ActionSheet_LaunchNewGroupPay"
    static let GroupPay_CloseUnpayNotify_Fail_Tips = "GroupPay_CloseUnpayNotify_Fail_Tips"
    static let GroupPay_Contact_SelfDisplayName_Suffix = "GroupPay_Contact_SelfDisplayName_Suffix"
    static let GroupPay_GetOrder_Detail_Fail_Tips = "GroupPay_GetOrder_Detail_Fail_Tips"
    static let GroupPay_Intro_Title = "GroupPay_Intro_Title"
    static let GroupPay_IntroViewController_DescContent = "GroupPay_IntroViewController_DescContent"
    static let GroupPay_IntroViewController_ViewHistoryContent = "GroupPay_IntroViewController_ViewHistoryContent"
    static let GroupPay_Launch_AA_Fail_Tips = "GroupPay_Launch_AA_Fail_Tips"
    static let GroupPay_Launch_AAChangeToActivityMode_Tips = "GroupPay_Launch_AAChangeToActivityMode_Tips"
    static let GroupPay_Launch_Activity_Cannot_SelectAllMemberAsPayer_Tips = "GroupPay_Launch_Activity_Cannot_SelectAllMemberAsPayer_Tips"
    static let GroupPay_Launch_Activity_Cannot_SelectAllMemberAsReceiver_Tips = "GroupPay_Launch_Activity_Cannot_SelectAllMemberAsReceiver_Tips"
    static let GroupPay_Launch_ActivityAA_PayerSection_Member_PreSelect_Title_Format = "GroupPay_Launch_ActivityAA_PayerSection_Member_PreSelect_Title_Format"
    static let GroupPay_Launch_ActivityAA_PayerSection_Member_Title_Format = "GroupPay_Launch_ActivityAA_PayerSection_Member_Title_Format"
    static let GroupPay_Launch_ActivityAA_PayerSection_Title = "GroupPay_Launch_ActivityAA_PayerSection_Title"
    static let GroupPay_Launch_ActivityAA_TotalAmount_Format = "GroupPay_Launch_ActivityAA_TotalAmount_Format"
    static let GroupPay_Launch_ActivityAA_TotalAmount_Tips_Format = "GroupPay_Launch_ActivityAA_TotalAmount_Tips_Format"
    static let GroupPay_Launch_ActivityModeChangeToAAMode_Tips = "GroupPay_Launch_ActivityModeChangeToAAMode_Tips"
    static let GroupPay_Launch_AddMember_Tips_Label_Text = "GroupPay_Launch_AddMember_Tips_Label_Text"
    static let GroupPay_Launch_CommonAA_ActivityTextField_Default = "GroupPay_Launch_CommonAA_ActivityTextField_Default"
    static let GroupPay_Launch_CommonAA_AmountField_PlaceHolder = "GroupPay_Launch_CommonAA_AmountField_PlaceHolder"
    static let GroupPay_Launch_CommonAA_TotalAmount_DefaultTips_Format = "GroupPay_Launch_CommonAA_TotalAmount_DefaultTips_Format"
    static let GroupPay_Launch_CommonAA_TotalAmount_Mode_Tips = "GroupPay_Launch_CommonAA_TotalAmount_Mode_Tips"
    static let GroupPay_Launch_CommonAA_TotalAmount_Tips = "GroupPay_Launch_CommonAA_TotalAmount_Tips"
    static let GroupPay_Launch_CommonAA_TotalMember_ModifiedTips_Format = "GroupPay_Launch_CommonAA_TotalMember_ModifiedTips_Format"
    static let GroupPay_Launch_MemberLabel_Text = "GroupPay_Launch_MemberLabel_Text"
    static let GroupPay_Launch_MoneyLable_Text = "GroupPay_Launch_MoneyLable_Text"
    static let GroupPay_Launch_StartLaunch_Btn_Ttile = "GroupPay_Launch_StartLaunch_Btn_Ttile"
    static let GroupPay_Launch_ViewController_Title = "GroupPay_Launch_ViewController_Title"
    static let GroupPay_MemberFillMoney_ViewController_CleanUpAlert_Cancel = "GroupPay_MemberFillMoney_ViewController_CleanUpAlert_Cancel"
    static let GroupPay_MemberFillMoney_ViewController_CleanUpAlert_Confirm = "GroupPay_MemberFillMoney_ViewController_CleanUpAlert_Confirm"
    static let GroupPay_MemberFillMoney_ViewController_CleanUpAlert_Title = "GroupPay_MemberFillMoney_ViewController_CleanUpAlert_Title"
    static let GroupPay_MemberFillMoney_ViewController_CleanupBtn_Title = "GroupPay_MemberFillMoney_ViewController_CleanupBtn_Title"
    static let GroupPay_MemberFillMoney_ViewController_Title = "GroupPay_MemberFillMoney_ViewController_Title"
    static let GroupPay_MemberFillMoney_ViewController_TotalAmount_Format = "GroupPay_MemberFillMoney_ViewController_TotalAmount_Format"
    static let GroupPay_MsgSession_Scene_Text = "GroupPay_MsgSession_Scene_Text"
    static let GroupPay_OrderDetailVC_CommonAA_Title_Format = "GroupPay_OrderDetailVC_CommonAA_Title_Format"
    static let GroupPay_OrderDetailVC_CommonAA_Title_Short_Format = "GroupPay_OrderDetailVC_CommonAA_Title_Short_Format"
    static let GroupPay_OrderHistory_ActionSheet_Launch = "GroupPay_OrderHistory_ActionSheet_Launch"
    static let GroupPay_OrderHistory_ActionSheet_Pay = "GroupPay_OrderHistory_ActionSheet_Pay"
    static let GroupPay_OrderHistory_Amount_Unit = "GroupPay_OrderHistory_Amount_Unit"
    static let GroupPay_OrderHistory_Default_ChatroomName = "GroupPay_OrderHistory_Default_ChatroomName"
    static let GroupPay_OrderHistory_Default_Theme = "GroupPay_OrderHistory_Default_Theme"
    static let GroupPay_OrderHistory_Fail_Tips = "GroupPay_OrderHistory_Fail_Tips"
    static let GroupPay_OrderHistory_H5AARecord_EnteranceTitle = "GroupPay_OrderHistory_H5AARecord_EnteranceTitle"
    static let GroupPay_OrderHistory_Link_Format = "GroupPay_OrderHistory_Link_Format"
    static let GroupPay_OrderHistory_NoRecord_Tips = "GroupPay_OrderHistory_NoRecord_Tips"
    static let GroupPay_OrderHistory_Status_Close = "GroupPay_OrderHistory_Status_Close"
    static let GroupPay_OrderHistory_Status_Finish = "GroupPay_OrderHistory_Status_Finish"
    static let GroupPay_OrderHistory_Status_Normal = "GroupPay_OrderHistory_Status_Normal"
    static let GroupPay_OrderHistory_Status_Overtime = "GroupPay_OrderHistory_Status_Overtime"
    static let GroupPay_OrderHistory_Status_Paid = "GroupPay_OrderHistory_Status_Paid"
    static let GroupPay_OrderHistory_Status_WaittingPay = "GroupPay_OrderHistory_Status_WaittingPay"
    static let GroupPay_OrderHistory_VC_Title_Launch = "GroupPay_OrderHistory_VC_Title_Launch"
    static let GroupPay_OrderHistory_VC_Title_Pay = "GroupPay_OrderHistory_VC_Title_Pay"
    static let GroupPay_OrderStatusVC_AA_HasPay_Content_Format = "GroupPay_OrderStatusVC_AA_HasPay_Content_Format"
    static let GroupPay_OrderStatusVC_AA_Receiver_HasReceipt_MainContent = "GroupPay_OrderStatusVC_AA_Receiver_HasReceipt_MainContent"
    static let GroupPay_OrderStatusVC_AA_Receiver_NotReceipt_MainContent_HasPay_Format = "GroupPay_OrderStatusVC_AA_Receiver_NotReceipt_MainContent_HasPay_Format"
    static let GroupPay_OrderStatusVC_AA_Receiver_NotReceipt_MainContent_NoPay = "GroupPay_OrderStatusVC_AA_Receiver_NotReceipt_MainContent_NoPay"
    static let GroupPay_OrderStatusVC_AA_Title_Format = "GroupPay_OrderStatusVC_AA_Title_Format"
    static let GroupPay_OrderStatusVC_ActivityAA_PerAmount_Tips = "GroupPay_OrderStatusVC_ActivityAA_PerAmount_Tips"
    static let GroupPay_OrderStatusVC_ActivityAA_Receiver_NotReceipt_Launcher_DefaultTips = "GroupPay_OrderStatusVC_ActivityAA_Receiver_NotReceipt_Launcher_DefaultTips"
    static let GroupPay_OrderStatusVC_ActivityAA_Receiver_NotReceipt_Launcher_TipsLink = "GroupPay_OrderStatusVC_ActivityAA_Receiver_NotReceipt_Launcher_TipsLink"
    static let GroupPay_OrderStatusVC_CloseOrder_Alert_BtnTitle = "GroupPay_OrderStatusVC_CloseOrder_Alert_BtnTitle"
    static let GroupPay_OrderStatusVC_CloseOrder_Alert_Title = "GroupPay_OrderStatusVC_CloseOrder_Alert_Title"
    static let GroupPay_OrderStatusVC_CloseOrder_Fail_Tips = "GroupPay_OrderStatusVC_CloseOrder_Fail_Tips"
    static let GroupPay_OrderStatusVC_CloseOrderFromSysMsg_Success = "GroupPay_OrderStatusVC_CloseOrderFromSysMsg_Success"
    static let GroupPay_OrderStatusVC_CloseUnPayNotifyFromSysMsg_Confirm = "GroupPay_OrderStatusVC_CloseUnPayNotifyFromSysMsg_Confirm"
    static let GroupPay_OrderStatusVC_CloseUnPayNotifyFromSysMsg_Tips = "GroupPay_OrderStatusVC_CloseUnPayNotifyFromSysMsg_Tips"
    static let GroupPay_OrderStatusVC_CommonAA_HasFinish_Tips = "GroupPay_OrderStatusVC_CommonAA_HasFinish_Tips"
    static let GroupPay_OrderStatusVC_CommonAA_WaittingForPay_Content_Format = "GroupPay_OrderStatusVC_CommonAA_WaittingForPay_Content_Format"
    static let GroupPay_OrderStatusVC_More_CloseOrder = "GroupPay_OrderStatusVC_More_CloseOrder"
    static let GroupPay_OrderStatusVC_Notiner_Tips = "GroupPay_OrderStatusVC_Notiner_Tips"
    static let GroupPay_OrderStatusVC_OrderClose_Tips = "GroupPay_OrderStatusVC_OrderClose_Tips"
    static let GroupPay_OrderStatusVC_OrderOvertime_Tips = "GroupPay_OrderStatusVC_OrderOvertime_Tips"
    static let GroupPay_OrderStatusVC_PayBtn_Title = "GroupPay_OrderStatusVC_PayBtn_Title"
    static let GroupPay_OrderStatusVC_PaySuccess_Tips = "GroupPay_OrderStatusVC_PaySuccess_Tips"
    static let GroupPay_OrderStatusVC_SendPayNotify_Link_Format = "GroupPay_OrderStatusVC_SendPayNotify_Link_Format"
    static let GroupPay_OrderStatusVC_TableView_AA_HeaderTitle_HasPay_Format = "GroupPay_OrderStatusVC_TableView_AA_HeaderTitle_HasPay_Format"
    static let GroupPay_OrderStatusVC_TableView_AA_HeaderTitle_NotPay_Format = "GroupPay_OrderStatusVC_TableView_AA_HeaderTitle_NotPay_Format"
    static let GroupPay_OrderStatusVC_TableView_Cell_HasPay_Format = "GroupPay_OrderStatusVC_TableView_Cell_HasPay_Format"
    static let GroupPay_OrderStatusVC_TableView_Cell_HasReturn_Format = "GroupPay_OrderStatusVC_TableView_Cell_HasReturn_Format"
    static let GroupPay_OrderStatusVC_TableView_Cell_WaittingForPay_Format = "GroupPay_OrderStatusVC_TableView_Cell_WaittingForPay_Format"
    static let GroupPay_OrderStatusVC_ViewController_Title = "GroupPay_OrderStatusVC_ViewController_Title"
    static let GroupPay_PayDetail_PayConfirmDetail_Tips_Format = "GroupPay_PayDetail_PayConfirmDetail_Tips_Format"
    static let GroupPay_Payment_Self_Wording = "GroupPay_Payment_Self_Wording"
    static let GroupPay_Payment_SystemMsgContent_Format = "GroupPay_Payment_SystemMsgContent_Format"
    static let GroupPay_PayNotify_ConfirmView_Tips = "GroupPay_PayNotify_ConfirmView_Tips"
    static let GroupPay_PayNotify_ConfirmView_Title = "GroupPay_PayNotify_ConfirmView_Title"
    static let GroupPay_Prepay_Fail_Tips = "GroupPay_Prepay_Fail_Tips"
    static let GroupPay_SelectAll_OutOfMaxTips_ConfirmBtn_Title = "GroupPay_SelectAll_OutOfMaxTips_ConfirmBtn_Title"
    static let GroupPay_SelectAll_OutOfMaxTips_format = "GroupPay_SelectAll_OutOfMaxTips_format"
    static let GroupPay_SelectContact_Invalid_Tips = "GroupPay_SelectContact_Invalid_Tips"
    static let GroupPay_SelectMember_ALertView_Title = "GroupPay_SelectMember_ALertView_Title"
    static let GroupPay_SelectMember_SearchField_PlaceHolder = "GroupPay_SelectMember_SearchField_PlaceHolder"
    static let GroupPay_SelectMember_ToolBar_SelectAll = "GroupPay_SelectMember_ToolBar_SelectAll"
    static let GroupPay_SelectMember_ToolBar_SelectAllTips = "GroupPay_SelectMember_ToolBar_SelectAllTips"
    static let GroupPay_SelectMember_ViewController_SelectPayer_Title = "GroupPay_SelectMember_ViewController_SelectPayer_Title"
    static let GroupPay_SelectMember_ViewController_SelectReceiver_Title = "GroupPay_SelectMember_ViewController_SelectReceiver_Title"
    static let GroupPay_SelectMember_ViewController_Title = "GroupPay_SelectMember_ViewController_Title"
    static let GroupPay_SendPayNotify_Fail_Tips = "GroupPay_SendPayNotify_Fail_Tips"
    static let GroupPay_Session_HeaderTitle = "GroupPay_Session_HeaderTitle"
    static let GroupPay_SessionSelectViewController_Title = "GroupPay_SessionSelectViewController_Title"
    static let GroupPay_UnNormalOrderStatus_SubTitle_Format = "GroupPay_UnNormalOrderStatus_SubTitle_Format"
}
