//
//  LocalizationStrings+Album.swift
//  WeChatSwift
//
//  Created by xu.shuifeng on 2019/9/10.
//  Copyright © 2019 alexiscn. All rights reserved.
//

import Foundation

extension LocalizationStrings {
    static let Album_Background_HasLiked = "Album_Background_HasLiked"
    static let Album_Background_Select = "Album_Background_Select"
    static let Album_Background_SystemRecommand = "Album_Background_SystemRecommand"
    static let Album_Background_SystemRecommandTip = "Album_Background_SystemRecommandTip"
    static let Album_Change_Cover_Tip = "Album_Change_Cover_Tip"
    static let Album_ChangeBG_Title = "Album_ChangeBG_Title"
    static let Album_ChangeBkg = "Album_ChangeBkg"
    static let Album_Comment_Btn = "Album_Comment_Btn"
    static let Album_Comment_Btn_Stranger = "Album_Comment_Btn_Stranger"
    static let Album_Comment_Delete_Tip = "Album_Comment_Delete_Tip"
    static let Album_Comment_LikeBG = "Album_Comment_LikeBG"
    static let Album_Comment_View_Title = "Album_Comment_View_Title"
    static let Album_CommentList_Comment_Delete_Tip = "Album_CommentList_Comment_Delete_Tip"
    static let Album_CommentList_Ignore_Notification = "Album_CommentList_Ignore_Notification"
    static let Album_CommentList_Notification_Set_Fail = "Album_CommentList_Notification_Set_Fail"
    static let Album_CommentList_Notification_Set_Success = "Album_CommentList_Notification_Set_Success"
    static let Album_CommentList_Notification_Shield_Tips = "Album_CommentList_Notification_Shield_Tips"
    static let Album_CommentList_Object_Delete_Tip = "Album_CommentList_Object_Delete_Tip"
    static let Album_CommentList_Restore_Notification = "Album_CommentList_Restore_Notification"
    static let Album_CommentListTitle = "Album_CommentListTitle"
    static let Album_DeleteConfirm = "Album_DeleteConfirm"
    static let Album_DeleteConfirmTimeline = "Album_DeleteConfirmTimeline"
    static let Album_DeleteFail = "Album_DeleteFail"
    static let Album_DeleteOK = "Album_DeleteOK"
    static let Album_DeleteSightConfirm = "Album_DeleteSightConfirm"
    static let Album_Deleting = "Album_Deleting"
    static let Album_DisableTip = "Album_DisableTip"
    static let Album_ExposeComfirm = "Album_ExposeComfirm"
    static let Album_ExposeOK = "Album_ExposeOK"
    static let Album_Feedback_Tip = "Album_Feedback_Tip"
    static let Album_Forward = "Album_Forward"
    static let Album_Has_With_You = "Album_Has_With_You"
    static let Album_Intro = "Album_Intro"
    static let Album_Like_Background = "Album_Like_Background"
    static let Album_Like_Btn = "Album_Like_Btn"
    static let Album_Like_Btn_HasLiked = "Album_Like_Btn_HasLiked"
    static let Album_Like_Btn_Liked = "Album_Like_Btn_Liked"
    static let Album_LoadingTip = "Album_LoadingTip"
    static let Album_LoadMore = "Album_LoadMore"
    static let Album_Make_Private = "Album_Make_Private"
    static let Album_Make_PrivateFail = "Album_Make_PrivateFail"
    static let Album_Make_PrivateOK = "Album_Make_PrivateOK"
    static let Album_Make_Public = "Album_Make_Public"
    static let Album_Make_PublicFail = "Album_Make_PublicFail"
    static let Album_Make_PublicOK = "Album_Make_PublicOK"
    static let Album_Make_Sight_Private = "Album_Make_Sight_Private"
    static let Album_Make_Sight_Public = "Album_Make_Sight_Public"
    static let Album_MessageList = "Album_MessageList"
    static let Album_MessageTipFormat = "Album_MessageTipFormat"
    static let Album_NoMoreData = "Album_NoMoreData"
    static let Album_NoMoreTip = "Album_NoMoreTip"
    static let Album_Notification_ShowInMainTab = "Album_Notification_ShowInMainTab"
    static let Album_Notification_ShowInMainTab_Explain = "Album_Notification_ShowInMainTab_Explain"
    static let Album_OneMessageTip = "Album_OneMessageTip"
    static let Album_RecentLimitSubTip_GoSetting = "Album_RecentLimitSubTip_GoSetting"
    static let Album_RecentLimitTip = "Album_RecentLimitTip"
    static let Album_RecentLimitTip_ThreeDays_ToFriend = "Album_RecentLimitTip_ThreeDays_ToFriend"
    static let Album_RecentLimitTip_ToFriend = "Album_RecentLimitTip_ToFriend"
    static let Album_ReSend = "Album_ReSend"
    static let Album_ReSend_Btn = "Album_ReSend_Btn"
    static let Album_RestoreDefaultBG = "Album_RestoreDefaultBG"
    static let Album_RestoreDefaultBG_Confirm = "Album_RestoreDefaultBG_Confirm"
    static let Album_SaveToPhotoLibrary = "Album_SaveToPhotoLibrary"
    static let Album_SaySomething = "Album_SaySomething"
    static let Album_Select_Contack = "Album_Select_Contack"
    static let Album_Select_Max_Format = "Album_Select_Max_Format"
    static let Album_Select_NoOne_AfterFilterIgoneContact = "Album_Select_NoOne_AfterFilterIgoneContact"
    static let Album_Select_Recommend = "Album_Select_Recommend"
    static let Album_SettingBK = "Album_SettingBK"
    static let Album_Text_Repost_Tip = "Album_Text_Repost_Tip"
    static let Album_Text_Send_Too_Fast = "Album_Text_Send_Too_Fast"
    static let Album_Text_Spam = "Album_Text_Spam"
    static let Album_Text_Too_Much = "Album_Text_Too_Much"
    static let Album_ThisIsLastPic = "Album_ThisIsLastPic"
    static let Album_Total_Image_HomePage = "Album_Total_Image_HomePage"
    static let Album_Touch_Top_Tip = "Album_Touch_Top_Tip"
    static let Album_UPloadFail_Notify_Resent_Ask = "Album_UPloadFail_Notify_Resent_Ask"
    static let Album_UPloadFailMessageTip = "Album_UPloadFailMessageTip"
    static let Album_UPloadFailNotity = "Album_UPloadFailNotity"
    static let Album_Video_Time_MiniuteAndSecond_Format = "Album_Video_Time_MiniuteAndSecond_Format"
    static let Album_Video_Time_Miniutes_Format = "Album_Video_Time_Miniutes_Format"
    static let Album_Video_Time_Seconds_Format = "Album_Video_Time_Seconds_Format"
    static let Album_View_Blacklist = "Album_View_Blacklist"
    static let Album_View_Outsider = "Album_View_Outsider"
    static let Album_ViewAlbumTimeline = "Album_ViewAlbumTimeline"
    static let Album_WhoLikeYours = "Album_WhoLikeYours"
    static let Album_With_Me = "Album_With_Me"
    static let Album_Write_Secret_Success = "Album_Write_Secret_Success"
    static let Album_WriteTextTitle = "Album_WriteTextTitle"
    static let Album_Year_Section_Format = "Album_Year_Section_Format"
    static let AlbumName_all_photos = "AlbumName_all_photos"
}
