//
//  LocalizationStrings+Backup.swift
//  WeChatSwift
//
//  Created by xu.shuifeng on 2019/9/10.
//  Copyright © 2019 alexiscn. All rights reserved.
//

import Foundation

extension LocalizationStrings {
    static let Backup_Alert_Cancel_Backup_Confirm_Cancel = "Backup_Alert_Cancel_Backup_Confirm_Cancel"
    static let Backup_Alert_Cancel_Backup_Message = "Backup_Alert_Cancel_Backup_Message"
    static let Backup_Alert_Cancel_Backup_Title = "Backup_Alert_Cancel_Backup_Title"
    static let Backup_Alert_Cancel_Recover_Data_Message = "Backup_Alert_Cancel_Recover_Data_Message"
    static let Backup_Alert_Cancel_Recover_Data_Title = "Backup_Alert_Cancel_Recover_Data_Title"
    static let Backup_Alert_Cancel_Recover_Transfer_Confrim_Cancel = "Backup_Alert_Cancel_Recover_Transfer_Confrim_Cancel"
    static let Backup_Alert_Cancel_Recover_Transfer_Message = "Backup_Alert_Cancel_Recover_Transfer_Message"
    static let Backup_Alert_Cancel_Recover_Transfer_Title = "Backup_Alert_Cancel_Recover_Transfer_Title"
    static let Backup_Alert_Interruption_BatteryIsNotEnough = "Backup_Alert_Interruption_BatteryIsNotEnough"
    static let Backup_Alert_Interruption_Migrated_CostTime = "Backup_Alert_Interruption_Migrated_CostTime"
    static let Backup_Alert_Interruption_NoSession = "Backup_Alert_Interruption_NoSession"
    static let Backup_Alert_Interruption_ShouldRecoverData = "Backup_Alert_Interruption_ShouldRecoverData"
    static let Backup_Alert_Stop_Recover_Data_Message = "Backup_Alert_Stop_Recover_Data_Message"
    static let Backup_Alert_Stop_Recover_Data_Title = "Backup_Alert_Stop_Recover_Data_Title"
    static let Backup_Cancel_Recover = "Backup_Cancel_Recover"
    static let Backup_Computer_Network = "Backup_Computer_Network"
    static let Backup_Continue_Recover = "Backup_Continue_Recover"
    static let Backup_Delete_Cancel_Delete = "Backup_Delete_Cancel_Delete"
    static let Backup_Delete_Confirm_Delete = "Backup_Delete_Confirm_Delete"
    static let Backup_Delete_Continue_Delete = "Backup_Delete_Continue_Delete"
    static let Backup_Delete_Delete_Confirm_Tip = "Backup_Delete_Delete_Confirm_Tip"
    static let Backup_Delete_Delete_Confirm_Tip2 = "Backup_Delete_Delete_Confirm_Tip2"
    static let Backup_Delete_Delete_Interrupt = "Backup_Delete_Delete_Interrupt"
    static let Backup_Delete_Delete_Log_Ing = "Backup_Delete_Delete_Log_Ing"
    static let Backup_Delete_End_Delete = "Backup_Delete_End_Delete"
    static let Backup_Delete_End_Delete_Tip = "Backup_Delete_End_Delete_Tip"
    static let Backup_Delete_End_Delete_Title = "Backup_Delete_End_Delete_Title"
    static let Backup_Delete_EnterBackground_DeleteTips = "Backup_Delete_EnterBackground_DeleteTips"
    static let Backup_Delete_SessionCount_And_TotalCount = "Backup_Delete_SessionCount_And_TotalCount"
    static let Backup_Delete_Start_Delete = "Backup_Delete_Start_Delete"
    static let Backup_Delete_Success_Delete_Size = "Backup_Delete_Success_Delete_Size"
    static let Backup_Delete_Will_Finish_Soon = "Backup_Delete_Will_Finish_Soon"
    static let Backup_EnterBackground_BackupTips = "Backup_EnterBackground_BackupTips"
    static let Backup_EnterBackground_RecoverTips = "Backup_EnterBackground_RecoverTips"
    static let Backup_Entry_Tip = "Backup_Entry_Tip"
    static let Backup_EntryView_Minimize = "Backup_EntryView_Minimize"
    static let Backup_Help_Show_LookForReason_HowToDo = "Backup_Help_Show_LookForReason_HowToDo"
    static let Backup_Network_Error = "Backup_Network_Error"
    static let Backup_Not_In_Wifi = "Backup_Not_In_Wifi"
    static let Backup_Notice_Click_Continue_Backup_Transfer = "Backup_Notice_Click_Continue_Backup_Transfer"
    static let Backup_Notice_Click_Continue_Recover_Transfer = "Backup_Notice_Click_Continue_Recover_Transfer"
    static let Backup_Phone_Network = "Backup_Phone_Network"
    static let Backup_Program_Error = "Backup_Program_Error"
    static let Backup_Recover_Other_Time = "Backup_Recover_Other_Time"
    static let Backup_Select_All_Content = "Backup_Select_All_Content"
    static let Backup_Select_All_Time = "Backup_Select_All_Time"
    static let Backup_Select_Begin_Time_Tip = "Backup_Select_Begin_Time_Tip"
    static let Backup_Select_Content_Select_Content_Title = "Backup_Select_Content_Select_Content_Title"
    static let Backup_Select_Content_Select_Time_Title = "Backup_Select_Content_Select_Time_Title"
    static let Backup_Select_Content_Title = "Backup_Select_Content_Title"
    static let Backup_Select_End_Time_Tip = "Backup_Select_End_Time_Tip"
    static let Backup_Select_Only_Text = "Backup_Select_Only_Text"
    static let Backup_Select_Pick_Begin_Time = "Backup_Select_Pick_Begin_Time"
    static let Backup_Select_Pick_End_Time = "Backup_Select_Pick_End_Time"
    static let Backup_Select_Session = "Backup_Select_Session"
    static let Backup_Select_Session_Empty = "Backup_Select_Session_Empty"
    static let Backup_Select_Show_Content_Tip = "Backup_Select_Show_Content_Tip"
    static let Backup_Select_Show_Number_Tip = "Backup_Select_Show_Number_Tip"
    static let Backup_Select_Show_Time_Tip = "Backup_Select_Show_Time_Tip"
    static let Backup_Select_Specific_Time = "Backup_Select_Specific_Time"
    static let Backup_Select_Time_Invalid = "Backup_Select_Time_Invalid"
    static let Backup_Select_Time_Session_Empty = "Backup_Select_Time_Session_Empty"
    static let Backup_Select_Time_Title = "Backup_Select_Time_Title"
    static let Backup_Start_Backup = "Backup_Start_Backup"
    static let Backup_Start_Import = "Backup_Start_Import"
    static let Backup_Start_Recover = "Backup_Start_Recover"
    static let Backup_State_Backup_Data_Prepare = "Backup_State_Backup_Data_Prepare"
    static let Backup_State_Backup_Data_Prepare_Error = "Backup_State_Backup_Data_Prepare_Error"
    static let Backup_State_Backup_Disconnect_When_Transfer = "Backup_State_Backup_Disconnect_When_Transfer"
    static let Backup_State_Backup_Finish = "Backup_State_Backup_Finish"
    static let Backup_State_Backup_Finish_Tip = "Backup_State_Backup_Finish_Tip"
    static let Backup_State_Backup_Transfer = "Backup_State_Backup_Transfer"
    static let Backup_State_Backup_Transfer_Disconnect = "Backup_State_Backup_Transfer_Disconnect"
    static let Backup_State_Backup_Transfer_Disconnect_Banner = "Backup_State_Backup_Transfer_Disconnect_Banner"
    static let Backup_State_Connecting = "Backup_State_Connecting"
    static let Backup_State_Network_IsNotGood = "Backup_State_Network_IsNotGood"
    static let Backup_State_Network_IsReconnecting = "Backup_State_Network_IsReconnecting"
    static let Backup_State_Not_Close_Tip = "Backup_State_Not_Close_Tip"
    static let Backup_State_Not_Same_Account = "Backup_State_Not_Same_Account"
    static let Backup_State_Not_Same_Port = "Backup_State_Not_Same_Port"
    static let Backup_State_Not_Same_Wifi = "Backup_State_Not_Same_Wifi"
    static let Backup_State_Phone_Size_Not_Enough = "Backup_State_Phone_Size_Not_Enough"
    static let Backup_State_Recover_Data_Prepare = "Backup_State_Recover_Data_Prepare"
    static let Backup_State_Recover_Transfer = "Backup_State_Recover_Transfer"
    static let Backup_State_Recover_Transfer_Disconnect = "Backup_State_Recover_Transfer_Disconnect"
    static let Backup_State_Recover_Transfer_Disconnect_Banner = "Backup_State_Recover_Transfer_Disconnect_Banner"
    static let Backup_State_RecoverData_Confirm = "Backup_State_RecoverData_Confirm"
    static let Backup_State_RecoverData_Confirm_Tip = "Backup_State_RecoverData_Confirm_Tip"
    static let Backup_State_RecoverData_Error = "Backup_State_RecoverData_Error"
    static let Backup_State_RecoverData_Error_Tip = "Backup_State_RecoverData_Error_Tip"
    static let Backup_State_RecoverData_Finish = "Backup_State_RecoverData_Finish"
    static let Backup_State_RecoverData_Finish_Tip = "Backup_State_RecoverData_Finish_Tip"
    static let Backup_State_RecoverData_Perpare_Finish = "Backup_State_RecoverData_Perpare_Finish"
    static let Backup_State_RecoverData_Tip = "Backup_State_RecoverData_Tip"
    static let Backup_State_RecoverData_Transfer = "Backup_State_RecoverData_Transfer"
    static let Backup_State_Start_Backup = "Backup_State_Start_Backup"
    static let Backup_State_Start_Backup_All = "Backup_State_Start_Backup_All"
    static let Backup_State_Start_Backup_Selection = "Backup_State_Start_Backup_Selection"
    static let Backup_State_Start_Backup_Tip = "Backup_State_Start_Backup_Tip"
    static let Backup_State_Start_Recover = "Backup_State_Start_Recover"
    static let Backup_Stop_Recover = "Backup_Stop_Recover"
    static let Backup_User_Confirm = "Backup_User_Confirm"
    static let Bakcup_Select_Date = "Bakcup_Select_Date"
}
