//
//  LocalizationStrings+BindPhone.swift
//  WeChatSwift
//
//  Created by xu.shuifeng on 2019/9/10.
//  Copyright © 2019 alexiscn. All rights reserved.
//

import Foundation

extension LocalizationStrings {
    static let BindPhone_Alert_Cancel = "BindPhone_Alert_Cancel"
    static let BindPhone_Alert_SetPrivate = "BindPhone_Alert_SetPrivate"
    static let BindPhone_BadFormat = "BindPhone_BadFormat"
    static let BindPhone_Bind = "BindPhone_Bind"
    static let BindPhone_BindError_For_EU = "BindPhone_BindError_For_EU"
    static let BindPhone_BindFaild = "BindPhone_BindFaild"
    static let BindPhone_BindTip = "BindPhone_BindTip"
    static let BindPhone_BindTitle = "BindPhone_BindTitle"
    static let BindPhone_Bound = "BindPhone_Bound"
    static let BindPhone_Cancel_Alert_Msg = "BindPhone_Cancel_Alert_Msg"
    static let BindPhone_Cancel_Alert_Msg_For_NakedWx_Protect = "BindPhone_Cancel_Alert_Msg_For_NakedWx_Protect"
    static let BindPhone_Change_OK = "BindPhone_Change_OK"
    static let BindPhone_CountryNameChineseStrokes = "BindPhone_CountryNameChineseStrokes"
    static let BindPhone_Delete = "BindPhone_Delete"
    static let BindPhone_DeleteTip = "BindPhone_DeleteTip"
    static let BindPhone_FormatTip = "BindPhone_FormatTip"
    static let BindPhone_GetVerifyByVoice = "BindPhone_GetVerifyByVoice"
    static let BindPhone_GetVerifyVoiceLangSel = "BindPhone_GetVerifyVoiceLangSel"
    static let BindPhone_GetVerifyVoiceLanguage = "BindPhone_GetVerifyVoiceLanguage"
    static let BindPhone_GetVerifyVoiceTip = "BindPhone_GetVerifyVoiceTip"
    static let BindPhone_HasBind = "BindPhone_HasBind"
    static let BindPhone_HasBindButNoAddressBook = "BindPhone_HasBindButNoAddressBook"
    static let BindPhone_Holder = "BindPhone_Holder"
    static let BindPhone_NakedWx_BindPhone_Header_Tips = "BindPhone_NakedWx_BindPhone_Header_Tips"
    static let BindPhone_NakedWx_BindPhone_Success_Tips = "BindPhone_NakedWx_BindPhone_Success_Tips"
    static let BindPhone_NakedWx_BindPhone_Success_Title = "BindPhone_NakedWx_BindPhone_Success_Title"
    static let BindPhone_NakedWx_Logout_Alert_Msg = "BindPhone_NakedWx_Logout_Alert_Msg"
    static let BindPhone_NeedAdjust = "BindPhone_NeedAdjust"
    static let BindPhone_NewOpen = "BindPhone_NewOpen"
    static let BindPhone_NewPromote = "BindPhone_NewPromote"
    static let BindPhone_NewTitle = "BindPhone_NewTitle"
    static let BindPhone_NoSuchNumber = "BindPhone_NoSuchNumber"
    static let BindPhone_NotYetVerify = "BindPhone_NotYetVerify"
    static let BindPhone_NumberBound = "BindPhone_NumberBound"
    static let BindPhone_OK = "BindPhone_OK"
    static let BindPhone_OnlySetWxId_Logout_Alert_Msg_WxId = "BindPhone_OnlySetWxId_Logout_Alert_Msg_WxId"
    static let BindPhone_Open = "BindPhone_Open"
    static let BindPhone_PickCountryCode = "BindPhone_PickCountryCode"
    static let BindPhone_Privacy = "BindPhone_Privacy"
    static let BindPhone_Promote = "BindPhone_Promote"
    static let BindPhone_PublicWifiButton = "BindPhone_PublicWifiButton"
    static let BindPhone_PublicWifiPromote = "BindPhone_PublicWifiPromote"
    static let BindPhone_PublicWifiTitle = "BindPhone_PublicWifiTitle"
    static let BindPhone_SearchAddrBookDetail = "BindPhone_SearchAddrBookDetail"
    static let BindPhone_SearchAddrBookTitle = "BindPhone_SearchAddrBookTitle"
    static let BindPhone_SendVerifyFail = "BindPhone_SendVerifyFail"
    static let BindPhone_SetPrivate_FindMe = "BindPhone_SetPrivate_FindMe"
    static let BindPhone_SetPrivate_FindMe_CheckBox = "BindPhone_SetPrivate_FindMe_CheckBox"
    static let BindPhone_SetPrivate_PushFriend = "BindPhone_SetPrivate_PushFriend"
    static let BindPhone_SetPrivate_PushFriend_CheckBox = "BindPhone_SetPrivate_PushFriend_CheckBox"
    static let BindPhone_Skip = "BindPhone_Skip"
    static let BindPhone_StartVerify = "BindPhone_StartVerify"
    static let BindPhone_SyncAddressBookTip = "BindPhone_SyncAddressBookTip"
    static let BindPhone_SyncAddressBookToFF = "BindPhone_SyncAddressBookToFF"
    static let BindPhone_Unbind = "BindPhone_Unbind"
    static let BindPhone_UnBinding = "BindPhone_UnBinding"
    static let BindPhone_UnBindNo = "BindPhone_UnBindNo"
    static let BindPhone_UnBindTip = "BindPhone_UnBindTip"
    static let BindPhone_UnBindTitle = "BindPhone_UnBindTitle"
    static let BindPhone_UnBindYes = "BindPhone_UnBindYes"
    static let BindPhone_UnBoundDone = "BindPhone_UnBoundDone"
    static let BindPhone_UnBoundFaild = "BindPhone_UnBoundFaild"
    static let BindPhone_UnSupportNumber = "BindPhone_UnSupportNumber"
    static let BindPhone_Verify = "BindPhone_Verify"
    static let BindPhone_Verify_OK = "BindPhone_Verify_OK"
    static let BindPhone_VerifyFaild = "BindPhone_VerifyFaild"
    static let BindPhone_VerifyFaildTip = "BindPhone_VerifyFaildTip"
    static let BindPhone_Verifying = "BindPhone_Verifying"
    static let BindPhone_VerifyTip = "BindPhone_VerifyTip"
    static let BindPhone_VerifyTitle = "BindPhone_VerifyTitle"
    static let BindPhone_VerifyVoiceCall = "BindPhone_VerifyVoiceCall"
    static let BindPhone_VerifyVoiceTip = "BindPhone_VerifyVoiceTip"
    static let BindPhone_ViewAddrFriend = "BindPhone_ViewAddrFriend"
}
